package com.example.staylio_backend.model.enums;

public enum NotificationType {

    // BOOKING
    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    BOOKING_CHECKED_IN,
    BOOKING_CHECKED_OUT,
    BOOKING_REFUNDED,
    BOOKING_PAYMENT_SUCCESS,
    BOOKING_PAYMENT_FAILED,

    // REVIEW
    REVIEW_CREATED,
    REVIEW_REPLIED,
    REVIEW_HIDDEN,

    // ROOM IMAGE
    ROOM_IMAGE_PENDING,
    ROOM_IMAGE_CONFIRMED,
    ROOM_IMAGE_REJECTED,

    // VOUCHER
    VOUCHER_CREATED,
    VOUCHER_CONFIRMED,
    VOUCHER_REJECTED,
    VOUCHER_DISABLED,
    VOUCHER_EXPIRED,

    // HOTEL / BRANCH
    HOTEL_BRANCH_CREATED,
    HOTEL_BRANCH_CONFIRMED,
    HOTEL_BRANCH_REJECTED,

    HOTEL_BRAND_CREATED,
    HOTEL_BRAND_CONFIRMED,
    HOTEL_BRAND_REJECTED,

    // SYSTEM
    SYSTEM_NOTIFICATION
}