export enum NotificationType {
    BOOKING_CREATED = "BOOKING_CREATED",
    BOOKING_CONFIRMED = "BOOKING_CONFIRMED",
    BOOKING_CANCELLED = "BOOKING_CANCELLED",
    BOOKING_CHECKED_IN = "BOOKING_CHECKED_IN",
    BOOKING_CHECKED_OUT = "BOOKING_CHECKED_OUT",
    BOOKING_REFUNDED = "BOOKING_REFUNDED",
    BOOKING_PAYMENT_SUCCESS = "BOOKING_PAYMENT_SUCCESS",
    BOOKING_PAYMENT_FAILED = "BOOKING_PAYMENT_FAILED",

    // REVIEW
    REVIEW_CREATED = "REVIEW_CREATED",
    REVIEW_REPLIED = "REVIEW_REPLIED",
    REVIEW_HIDDEN = "REVIEW_HIDDEN",

    // ROOM IMAGE
    ROOM_IMAGE_PENDING = "ROOM_IMAGE_PENDING",
    ROOM_IMAGE_CONFIRMED = "ROOM_IMAGE_CONFIRMED",
    ROOM_IMAGE_REJECTED = "ROOM_IMAGE_REJECTED",

    // VOUCHER
    VOUCHER_CREATED = "VOUCHER_CREATED",
    VOUCHER_CONFIRMED = "VOUCHER_CONFIRMED",
    VOUCHER_REJECTED = "VOUCHER_REJECTED",
    VOUCHER_DISABLED = "VOUCHER_DISABLED",
    VOUCHER_EXPIRED = "VOUCHER_EXPIRED",

    // HOTEL / BRANCH
    HOTEL_BRANCH_CREATED = "HOTEL_BRANCH_CREATED",
    HOTEL_BRANCH_CONFIRMED = "HOTEL_BRANCH_CONFIRMED",
    HOTEL_BRANCH_REJECTED = "HOTEL_BRANCH_REJECTED",

    HOTEL_BRAND_CREATED = "HOTEL_BRAND_CREATED",
    HOTEL_BRAND_CONFIRMED = "HOTEL_BRAND_CONFIRMED",
    HOTEL_BRAND_REJECTED = "HOTEL_BRAND_REJECTED",

    // SYSTEM
    SYSTEM_NOTIFICATION = "SYSTEM_NOTIFICATION"
}