use staylio_db;

INSERT INTO hotels (manager_id, created_at, description, name, status, image_url) VALUES
    (1, NOW(), 'Khách sạn sang trọng tọa lạc ngay trung tâm quận 1 với view nhìn ra sông Sài Gòn tuyệt đẹp.', 'Saigon Grand Hotel', 'PENDING', 'https://images.unsplash.com/photo-1566073771259-6a8506099945'),
    (4, NOW(), 'Khu nghỉ dưỡng yên tĩnh bên bờ biển với các villa biệt lập và dịch vụ spa cao cấp.', 'Blue Ocean Resort', 'CONFIRMED', 'https://images.unsplash.com/photo-1540541338287-41700207dee6'),
    (5, NOW(), 'Không gian ấm cúng, thiết kế hiện đại phù hợp cho khách đi công tác dài ngày.', 'City Comfort Inn', 'REJECTED', 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4'),
    (6, NOW(), 'Trải nghiệm cuộc sống gần gũi với thiên nhiên tại các căn nhà gỗ trên cao.', 'Mountain Retreat Homestay', 'DELETED', 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2'),
    (7, NOW(), 'Khách sạn phong cách boutique với kiến trúc Đông Dương độc đáo và tinh tế.', 'Indochina Heritage Hotel', 'CONFIRMED', 'https://images.unsplash.com/photo-1544124499-58912cbddade'),
    (8, NOW(), 'Vị trí đắc địa gần sân bay, phòng ốc sạch sẽ, tiện nghi đầy đủ cho khách quá cảnh.', 'Airport Transit Hotel', 'CONFIRMED', 'https://images.unsplash.com/photo-1551882547-ff43c63efe81');

INSERT INTO hotel_branchs (address, branch_name, image_url, status, hotel_id, ward_id, created_at, updated_at) VALUES
                                                                                                                   ('123 Đường Lê Lợi, Quận 1', 'Chi nhánh Sài Gòn Center', 'https://images.unsplash.com/photo-1566073771259-6a8506099945', 'CONFIRMED', FLOOR(1 + (RAND() * 5)), FLOOR(1 + (RAND() * 5)), NOW(), NOW()),
                                                                                                                   ('456 Võ Nguyên Giáp, Sơn Trà', 'Chi nhánh Biển Mỹ Khê', 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b', 'CONFIRMED', FLOOR(1 + (RAND() * 5)), FLOOR(1 + (RAND() * 5)), NOW(), NOW()),
                                                                                                                   ('78 Trần Phú, Lộc Thọ', 'Chi nhánh Nha Trang Bay', 'https://images.unsplash.com/photo-1544124499-58912cbddade', 'PENDING', FLOOR(1 + (RAND() * 5)), FLOOR(1 + (RAND() * 5)), NOW(), NOW()),
                                                                                                                   ('12 Hùng Vương, TP. Huế', 'Chi nhánh Cố Đô', 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4', 'CONFIRMED', FLOOR(1 + (RAND() * 5)), FLOOR(1 + (RAND() * 5)), NOW(), NOW()),
                                                                                                                   ('09 Phan Chu Trinh, Đà Lạt', 'Chi nhánh Cao Nguyên', 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c', 'REJECTED', FLOOR(1 + (RAND() * 5)), FLOOR(1 + (RAND() * 5)), NOW(), NOW()),
                                                                                                                   ('32 Đường Hạ Long, Bãi Cháy', 'Chi nhánh Vịnh Hạ Long', 'https://images.unsplash.com/photo-1551882547-ff43c63efe81', 'CONFIRMED', FLOOR(1 + (RAND() * 5)), FLOOR(1 + (RAND() * 5)), NOW(), NOW()),
                                                                                                                   ('102 Quang Trung, TP. Vinh', 'Chi nhánh Nghệ An', 'https://images.unsplash.com/photo-1564501049412-61c2a3083791', 'CONFIRMED', FLOOR(1 + (RAND() * 5)), FLOOR(1 + (RAND() * 5)), NOW(), NOW()),
                                                                                                                   ('22 Hai Bà Trưng, Quận Hoàn Kiếm', 'Chi nhánh Hà Nội Phố', 'https://images.unsplash.com/photo-1571896349842-33c89424de2d', 'PENDING', FLOOR(1 + (RAND() * 5)), FLOOR(1 + (RAND() * 5)), NOW(), NOW()),
                                                                                                                   ('55 Nguyễn Văn Linh, Ninh Kiều', 'Chi nhánh Tây Đô', 'https://images.unsplash.com/photo-1590490359683-658d3d23f972', 'CONFIRMED', FLOOR(1 + (RAND() * 5)), FLOOR(1 + (RAND() * 5)), NOW(), NOW()),
                                                                                                                   ('88 Đường 30/4, Dương Đông', 'Chi nhánh Đảo Ngọc', 'https://images.unsplash.com/photo-1512918766674-ed62b9795a3c', 'DELETED', FLOOR(1 + (RAND() * 5)), FLOOR(1 + (RAND() * 5)), NOW(), NOW());