name: Backend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "staylio_backend/**"
      - ".github/workflows/backend-ci.yml"

  pull_request:
    branches: [ "main" ]
    paths:
      - "staylio_backend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: staylio_backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - run: mvn clean package -DskipTests